routes/web.php
  'uses' => '\App\Http\Controllers\Settings\SettingsController@deleteBackup',
  'as' => 'backup-delete'
]);

Route::get('/logout', [
    'uses' => '\App\Http\Controllers\Auth\LoginController@logout'
]);

  Route::post('/verify-2fa',[
    'as' => 'verify-2fa',
    'uses' => '\App\Http\Controllers\Profile\ProfileController@verify'
  ]);

	Route::post('/activate-2fa',[
		'uses' => '\App\Http\Controllers\Profile\ProfileController@activate',
		'as' => 'activate-2fa'
	]);

	Route::post('/enable-2fa',[
		'uses' => '\App\Http\Controllers\Profile\ProfileController@enable',
		'as' => 'enable-2fa'
	]);

	Route::post('/disable-2fa',[
		'uses' => '\App\Http\Controllers\Profile\ProfileController@disable',
		'as' => 'disable-2fa'
	]);

	Route::get('/2fa/instruction',[
		'uses' => '\App\Http\Controllers\Profile\ProfileController@instruction',
	]);


	Route::get('/',[
		'as'=> 'home',
		'uses'=> '\App\Http\Controllers\Dashboard\DashboardController@index',
	])->middleware('auth');

  /*
  | Stripe Subscription Routes
  */
	Route::get('/subscription',[
		'as'=> '/subscription',
		'uses'=> '\App\Http\Controllers\SubscriptionController@index',
	]);


	Route::get('/subscription/subscribe',[
		'as'=> '/subscription/subscribe',
		'uses'=> '\App\Http\Controllers\SubscriptionController@notSubscribed',
	]);

	Route::get('/subscription/stripe/{plan_id}',[
		'as'=> '/subscription/stripe',
		'uses'=> '\App\Http\Controllers\SubscriptionController@stripeCheckout',
	]);

	Route::post('/subscription/stripe/subscribe',[
		'as'=> '/subscription/stripe/subscribe',
		'uses'=> '\App\Http\Controllers\SubscriptionController@stripeSubscribe',
	]);

  Route::get('/subscription-invoice/{invoiceId}',[
    'uses' => '\App\Http\Controllers\SubscriptionController@stripeInvoice',
  ]);

  Route::get('/subscription-cancel/{subscriptionId}',[
    'uses' => '\App\Http\Controllers\SubscriptionController@cancelSubscription',
  ]);
	/*
	| Stripe Subscription Routes
	*/

  /*
  | Stripe | Stripe Planted Trees Routes Routes
  */
	Route::get('/trees',[
		'as'=> '/trees',
		'uses'=> '\App\Http\Controllers\Tree\TreeController@index',
	]);

  Route::get('/trees/add',[
		'as'=> '/trees/add',
		'uses'=> '\App\Http\Controllers\TreeController@add',
	]);

  Route::put('/trees/create',[
		'as'=> '/trees/create',
		'uses'=> '\App\Http\Controllers\TreeController@create',
	]);

  Route::resource('/category-tree', '\App\Http\Controllers\TreeCategoryController');

	/*
	| Stripe Planted Trees Routes
	*/

  /*
  | Premium Content Routes
  */
  Route::resource('/premium-content', '\App\Http\Controllers\PremiumContent\PremiumContentController')
  ->middleware('premium');
  /*
  | Premium Content Routes
  */

	/*
	|  Activitylog Route
	*/
	Route::resource('activity-log', '\App\Http\Controllers\Activitylog\ActivitylogController');
  /*
  |  Activitylog Route
  */


	/*
	| Profile Routes
	*/

  Route::resource('profile', '\App\Http\Controllers\Profile\ProfileController');

	Route::get('update-avatar/{id}',[
		'as' => 'update-avatar',
		'uses'=> '\App\Http\Controllers\Profile\ProfileController@showAvatar'
	]);

	Route::post('update-avatar/{id}', '\App\Http\Controllers\Profile\ProfileController@updateAvatar');

	Route::post('update-profile-login/{id}',[
		'uses'=> '\App\Http\Controllers\Profile\ProfileController@updateLogin',
		'as' => 'update-login',
	]);

/*
| Profile Routes
*/

// Socialite Authentication Route
Route::get('login/{provider}', '\App\Http\Controllers\Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', '\App\Http\Controllers\Auth\LoginController@handleProviderCallback');

#####################################ADMIN MANAGED SECTION##########################################
// Users Route
	Route::resource('user', '\App\Http\Controllers\UserController');
	Route::post('update-user-login/{id}',[
    'as' => 'user-login',
	'uses'=> '\App\Http\Controllers\UserController@userLogin']);
	Route::get('user/{id}/activity-log/',[
    'as' => 'user-activitlog',
	'uses'=> '\App\Http\Controllers\UserController@userActivityLog']);
  // Users Route


// Roles Route
	Route::resource('role', '\App\Http\Controllers\Role\RoleController');
	Route::post('/role-permission/{id}',[
		'as' => 'roles_permit',
		'uses' => '\App\Http\Controllers\Role\RoleController@assignPermission',
	]);
// Roles Route


// Permission Route
	Route::resource('permission', '\App\Http\Controllers\Permission\PermissionController');
  // Permission Route


// Payment Gateway Route
          Route::get('/subscription/plan',[
              'as' => '/subscription/plan',
              'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@viewStripePlans',
          ]);

          Route::get('/subscription/plan/create',[
              'as' => '/subscription/plan/create',
              'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@createStripePlan',
          ]);

          Route::post('/subscription/plan/create',[
              'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@storeStripePlan',
          ]);

          Route::get('/stripe/plan/edit/{plan_id}',[
              'as' => '/stripe/plan/edit',
              'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@editStripePlan',
          ]);

          Route::post('/stripe/plan/edit/{id}/{plan_id}',[
              'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@updateStripePlan',
          ]);

          Route::post('/stripe/plan/delete/{id}',[
            'as' => '/stripe/plan/delete',
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@deleteStripePlan',
          ]);

          Route::get('/subscribed-users',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@manageSubscribedUser',
          ]);

          Route::get('/user-subscription-invoice/{invoiceId}',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@subscriptionInvoice',
          ]);

          Route::get('/user-subscription-cancel/{subscription_id}',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@cancelSub',
          ]);

          Route::get('/subscription-income',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@manageIncome',
          ]);

          Route::get('/checkout-sample',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@checkoutSamples',
          ]);

          Route::get('/checkout-sample/article',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@download',
          ]);

          Route::get('/checkout-sample/response/{session_id}',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@responseCheckout',
            'as' => '/checkout-sample/response'
          ]);

// Payment Gateway Route

      	Route::resource('settings','\App\Http\Controllers\Settings\SettingsController');

      	Route::post('settings/app-name/update',[
      		'as' => 'settings/app-name/update',
      		'uses' => '\App\Http\Controllers\Settings\SettingsController@appNameUpdate',
      	]);
      	Route::post('settings/app-logo/update',[
      		'as' => 'settings/app-logo/update',
      		'uses' => '\App\Http\Controllers\Settings\SettingsController@appLogoUpdate',
      	]);

      	Route::post('settings/app-theme/update',[
      		'as' => 'settings/app-theme/update',
      		'uses' => '\App\Http\Controllers\Settings\SettingsController@appThemeUpdate',
      	]);

      	Route::post('settings/stripe-payment/update',[
      		'as' => 'settings/stripe-payment/update',
      		'uses' => '\App\Http\Controllers\Settings\SettingsController@stripePaymentUpdate',
      	]);

        Route::post('settings/auth-settings/update',[
      		'as' => 'settings/auth-settings/update',
      		'uses' => '\App\Http\Controllers\Settings\SettingsController@authSettingsUpdate',
      	]);

        // Premium Content
        Route::resource('/article', '\App\Http\Controllers\Article\ArticleController');
        Route::post('/article-image', '\App\Http\Controllers\Article\ArticleController@articleImageUpload');
        Route::resource('/category-article', '\App\Http\Controllers\Article\ArticleCategoryController');
#####################################ADMIN MANAGED SECTION##########################################

#####################################CRUD GENERATOR ROUTES##########################################
      Route::get('/crud-builder', [
        'as' => 'crud-builder',
        'uses' => '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder'
      ])->middleware('auth','web','role:admin','2fa');

      Route::get('/field-template',[
        'as' => 'field-template',
        'uses' => '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate'
      ])->middleware('auth','web','role:admin','2fa');

      Route::post('/generator-builder/generate', [
        'as' => 'generator-builder/generate',
        'uses' => '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate'
      ])->middleware('auth','web','role:admin','2fa');

      Route::post('/generator-builder/rollback', [
        'as' => 'generator-builder/rollback',
        'uses' => '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback'
      ])->middleware('auth','web','role:admin','2fa');

      Route::post('/model-check', [
        'as' => 'model-check',
        'uses' => '\App\Http\Controllers\CRUDController@checkModel'
      ]);

#####################################CRUD GENERATOR ROUTES##########################################

#####################################WEBHOOK ROUTE##########################################
Route::stripeWebhooks('stripe-webhook');
#####################################WEBHOOK ROUTE##########################################

Route::impersonate();

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\Traits\CausesActivity;
use Carbon\Carbon;

class Permission extends Model
{
    use LogsActivity;
    use CausesActivity;

    protected $fillable = ['name'];

    protected static $logFillable = true;

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->diffForHumans();
    }

    public function getUpdatedAtAttribute($value)
    {
        return Carbon::parse($value)->diffForHumans();
    }
}

app/Http/Controllers/Permission/PermissionController.php
<?php

namespace App\Http\Controllers\Permission;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use UxWeb\SweetAlert\SweetAlert;
use Auth;

class PermissionController extends Controller
{
    public function __construct()
    {
        if (setting('email_verification')) {
            $this->middleware(['verified']);
        }
        $this->middleware(['auth','web','permission:manage-permission','2fa']);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::all();
        return view('permission.index')->with('permissions', $permissions);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('permission.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        $this->validate($request, [
            'name' => 'required|regex:/^[a-zA-Z0-9\-_\.]+$/|min:4|unique:permissions',
        ],[
          'regex' => 'Invalid Entry! Only letters,underscores,hypens and numbers are allowed',
        ]);

        $this->permission =  Permission::create([
            'name' => str_replace(' ', '-', strtolower($request->name)),
        ]);

        // Logging activity for created role
        activity()->performedOn($this->permission)->withProperties(['name'=>$this->permission->name,'by'=>Auth::user()->username])->causedBy(Auth::user())->log('Permission was created');

        return redirect()->back()->with('success', 'Permission Created Successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->permission = Permission::findOrfail($id);
        return view('permission.edit')->with('permission', $this->permission);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        $permission = Permission::find($id);


        $this->validate($request, [
            'name' => 'required|regex:/^[a-zA-Z0-9\-_\.]+$/|min:4|unique:permissions,name,'.$permission->id,
        ],[
          'regex' => 'Invalid Entry! Only letters,underscores,hypens and numbers are allowed',
        ]);

        $permission->name = str_replace(' ', '-', strtolower($request->name));

        // Logging activity for created role
        activity()->performedOn($permission)->withProperties(['name'=>$permission->name,'by'=>Auth::user()->username])->causedBy(Auth::user())->log('Permission was updated');

        $permission->save();

        return redirect()->back()->with('success', 'Permission Updated Sucessfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->permission = Permission::find($id);

        //default permission cannot be deleted
        if (!$this->permission->removable) {
            alert()->error('This permission cannot be deleted')->persistent('Close');
            return redirect()->back();
        }

        $this->permission->delete();
        // Logging activity for created role
        activity()->performedOn($this->permission)->withProperties(['name'=>$this->permission->name,'by'=>Auth::user()->username])->causedBy(Auth::user())->log('Permission was deleted');

        return redirect()->back()->with('success', 'Permission Deleted Successfully');
    }
}

resources/views/permission/create.blade.php
@extends('layouts.template')

@section('title','Create Permission')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
		<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{__('app.permissions')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">{{__('app.home')}}</a></li>
              <li class="breadcrumb-item"><a href="{{route('permission.index')}}">{{__('app.permission')}}</a></li>
              <li class="breadcrumb-item active">{{__('app.create')}}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
      <div class="row">
        <!-- right column -->
        <div class="col-md-7 mx-auto">
            @include('layouts.includes.alerts')
            <form class="form-horizontal" method="POST" action="{{route('permission.store')}}">
                  @csrf
                  <!-- Permission Creation -->
                  <div class="card">
                    <div class="card-header with-border">
                      {{__('app.create_permission')}}
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="form-group ">
                          <div class="row">

                            <div class="col-sm-12">
                              <div class="form-group">
                                <input type="text" name="name" class="form-control" id="password" placeholder="{{__('app.name_of_permission')}}">
                                @if ($errors->has('permission'))
                                  <span class="invalid-feedback" role="alert">
                                      <strong>{{ $errors->first('permission') }}</strong>
                                  </span>
                                @endif
                              </div>
                              <div class="col-sm-8 mx-auto" ><button type="submit" class="btn btn-success text-white btn-outline-secondary col-sm-12">{{__('app.create_permission')}}</button></div>
                            </div>
                              </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                  </div>
                  <!-- Permission Creation -->
            </form>
            <!-- form end -->
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection

resources/views/permission/edit.blade.php
@extends('layouts.template')

@section('title','Edit Permission')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
		<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{__('app.permissions')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">{{__('app.home')}}</a></li>
              <li class="breadcrumb-item"><a href="{{route('permission.index')}}">{{__('app.permission')}}</a></li>
              <li class="breadcrumb-item active">{{__('app.edit')}}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
      <div class="row">
        <!-- right column -->
        <div class="col-md-7 mx-auto">
            @include('layouts.includes.alerts')
            <form class="form-horizontal" method="POST" action="{{route('permission.update',$permission->id)}}">
                @csrf
                @method('PUT')
              <!-- Permission Creation -->
                  <div class="card">
                    <div class="card-header with-border">
                      {{__('app.permission')}}
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">
                        <div class="form-group ">
                            <div  class="col-sm-12">
                                <input type="text" value="{{$permission->name}}"name="name" class="form-control" id="password" placeholder="{{__('app.name_of_permission')}}">
                                @if ($errors->has('permission'))
                                  <span class="invalid-feedback" role="alert">
                                      <strong>{{ $errors->first('permission') }}</strong>
                                  </span>
                                @endif
                            </div>
                      </div>
                      <div class="col-sm-8 mx-auto"><button type="submit" class="btn btn-success col-sm-12">{{__('app.edit_permission')}}</button></div>
                    </div>
                      <!-- /.card-body -->
              <!-- Permission Edit-->
                </div>
            </form>
            <!-- form end -->
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!--/.col (right) -->
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection

resources/views/permission/index.blade.php
@extends('layouts.template')

@section('title','Permission')
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
		<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{__('app.permissions')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">{{__('app.home')}}</a></li>
              <li class="breadcrumb-item"><a href="{{route('permission.index')}}">{{__('app.permission')}}</a></li>
              <li class="breadcrumb-item active">{{__('app.view')}}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          @include('layouts.includes.alerts')
          <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 mb-3">
                <a href="{{route('permission.create')}}" class="pull-right btn btn-primary">Create Permission</a>
              </div>

              <div class="col-md-12">
              <table id="dataTable" class="table table-hover table-borderless table-striped">
                <thead>
                <tr>
                  <th class="">{{__('app.id')}}</th>
                  <th class="">{{__('app.name')}}</th>
                  <th class="">{{__('app.action')}}</th>
                </tr>
              </thead>
              <tbody>
                @foreach($permissions as $permission)
                  <tr>
                    <td>{{$permission->id}}</td>
                    <td>{{$permission->name}}</td>
                    <td>
                      <div class="col-md-12">
                          <div class="row">
                            <div class="mx-1">
                                <a href="{{route('permission.edit',$permission->id)}}"><button class="btn btn-sm btn-info" data-toggle="tooltip"  data-placement="bottom" title="Edit {{__('app.permission')}}"/><i class="fa fa-edit text-white"></i></button></a>
                            </div>
                            @if($permission->removable)
                            <div class="mx-1">
                              <form action="{{route('permission.destroy',$permission->id)}}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-xs btn-danger btn-sm" data-toggle="tooltip"  data-placement="bottom" title="Delete {{__('app.permission')}}"/><i class='fa fa-trash text-white'></i></button>
                              </form>
                            </div>
                            @endif
                          </div>
                      </div>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
              </table>
                  </div>
              </div>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
    </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection
@section('script')
<script src="{{asset('js/datatable.js')}}" charset="utf-8"></script>
@endsection