routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Application Backup-ROUTES
Route::post('/backup-file',[
  'uses' => '\App\Http\Controllers\Settings\SettingsController@backupFiles',
  'as' => 'backup-files'
]);

Route::post('/backup-db',[
  'uses' => '\App\Http\Controllers\Settings\SettingsController@backupDb',
  'as' => 'backup-db'
]);

Route::post('/backup-download/{name}/{ext}',[
  'uses' => '\App\Http\Controllers\Settings\SettingsController@downloadBackup',
  'as' => 'backup-download'
]);

Route::post('/backup-delete/{name}/{ext}',[
  'uses' => '\App\Http\Controllers\Settings\SettingsController@deleteBackup',
  'as' => 'backup-delete'
]);

Route::get('/logout', [
    'uses' => '\App\Http\Controllers\Auth\LoginController@logout'
]);

  Route::post('/verify-2fa',[
    'as' => 'verify-2fa',
    'uses' => '\App\Http\Controllers\Profile\ProfileController@verify'
  ]);

	Route::post('/activate-2fa',[
		'uses' => '\App\Http\Controllers\Profile\ProfileController@activate',
		'as' => 'activate-2fa'
	]);

	Route::post('/enable-2fa',[
		'uses' => '\App\Http\Controllers\Profile\ProfileController@enable',
		'as' => 'enable-2fa'
	]);

	Route::post('/disable-2fa',[
		'uses' => '\App\Http\Controllers\Profile\ProfileController@disable',
		'as' => 'disable-2fa'
	]);

	Route::get('/2fa/instruction',[
		'uses' => '\App\Http\Controllers\Profile\ProfileController@instruction',
	]);


	Route::get('/',[
		'as'=> 'home',
		'uses'=> '\App\Http\Controllers\Dashboard\DashboardController@index',
	])->middleware('auth');

  /*
  | Stripe Subscription Routes
  */
	Route::get('/subscription',[
		'as'=> '/subscription',
		'uses'=> '\App\Http\Controllers\SubscriptionController@index',
	]);


	Route::get('/subscription/subscribe',[
		'as'=> '/subscription/subscribe',
		'uses'=> '\App\Http\Controllers\SubscriptionController@notSubscribed',
	]);

	Route::get('/subscription/stripe/{plan_id}',[
		'as'=> '/subscription/stripe',
		'uses'=> '\App\Http\Controllers\SubscriptionController@stripeCheckout',
	]);

	Route::post('/subscription/stripe/subscribe',[
		'as'=> '/subscription/stripe/subscribe',
		'uses'=> '\App\Http\Controllers\SubscriptionController@stripeSubscribe',
	]);

  Route::get('/subscription-invoice/{invoiceId}',[
    'uses' => '\App\Http\Controllers\SubscriptionController@stripeInvoice',
  ]);

  Route::get('/subscription-cancel/{subscriptionId}',[
    'uses' => '\App\Http\Controllers\SubscriptionController@cancelSubscription',
  ]);
	/*
	| Stripe Subscription Routes
	*/

  /*
  | Stripe | Stripe Planted Trees Routes Routes
  */
	Route::get('/trees',[
		'as'=> '/trees',
		'uses'=> '\App\Http\Controllers\Tree\TreeController@index',
	]);

  Route::get('/trees/add',[
		'as'=> '/trees/add',
		'uses'=> '\App\Http\Controllers\TreeController@add',
	]);

  Route::put('/trees/create',[
		'as'=> '/trees/create',
		'uses'=> '\App\Http\Controllers\TreeController@create',
	]);

  Route::resource('/category-tree', '\App\Http\Controllers\TreeCategoryController');

	/*
	| Stripe Planted Trees Routes
	*/

  /*
  | Premium Content Routes
  */
  Route::resource('/premium-content', '\App\Http\Controllers\PremiumContent\PremiumContentController')
  ->middleware('premium');
  /*
  | Premium Content Routes
  */

	/*
	|  Activitylog Route
	*/
	Route::resource('activity-log', '\App\Http\Controllers\Activitylog\ActivitylogController');
  /*
  |  Activitylog Route
  */


	/*
	| Profile Routes
	*/

  Route::resource('profile', '\App\Http\Controllers\Profile\ProfileController');

	Route::get('update-avatar/{id}',[
		'as' => 'update-avatar',
		'uses'=> '\App\Http\Controllers\Profile\ProfileController@showAvatar'
	]);

	Route::post('update-avatar/{id}', '\App\Http\Controllers\Profile\ProfileController@updateAvatar');

	Route::post('update-profile-login/{id}',[
		'uses'=> '\App\Http\Controllers\Profile\ProfileController@updateLogin',
		'as' => 'update-login',
	]);

/*
| Profile Routes
*/

// Socialite Authentication Route
Route::get('login/{provider}', '\App\Http\Controllers\Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', '\App\Http\Controllers\Auth\LoginController@handleProviderCallback');

#####################################ADMIN MANAGED SECTION##########################################
// Users Route
	Route::resource('user', '\App\Http\Controllers\UserController');
	Route::post('update-user-login/{id}',[
    'as' => 'user-login',
	'uses'=> '\App\Http\Controllers\UserController@userLogin']);
	Route::get('user/{id}/activity-log/',[
    'as' => 'user-activitlog',
	'uses'=> '\App\Http\Controllers\UserController@userActivityLog']);
  // Users Route


// Roles Route
	Route::resource('role', '\App\Http\Controllers\Role\RoleController');
	Route::post('/role-permission/{id}',[
		'as' => 'roles_permit',
		'uses' => '\App\Http\Controllers\Role\RoleController@assignPermission',
	]);
// Roles Route


// Permission Route
	Route::resource('permission', '\App\Http\Controllers\Permission\PermissionController');
  // Permission Route


// Payment Gateway Route
          Route::get('/subscription/plan',[
              'as' => '/subscription/plan',
              'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@viewStripePlans',
          ]);

          Route::get('/subscription/plan/create',[
              'as' => '/subscription/plan/create',
              'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@createStripePlan',
          ]);

          Route::post('/subscription/plan/create',[
              'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@storeStripePlan',
          ]);

          Route::get('/stripe/plan/edit/{plan_id}',[
              'as' => '/stripe/plan/edit',
              'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@editStripePlan',
          ]);

          Route::post('/stripe/plan/edit/{id}/{plan_id}',[
              'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@updateStripePlan',
          ]);

          Route::post('/stripe/plan/delete/{id}',[
            'as' => '/stripe/plan/delete',
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@deleteStripePlan',
          ]);

          Route::get('/subscribed-users',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@manageSubscribedUser',
          ]);

          Route::get('/user-subscription-invoice/{invoiceId}',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@subscriptionInvoice',
          ]);

          Route::get('/user-subscription-cancel/{subscription_id}',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@cancelSub',
          ]);

          Route::get('/subscription-income',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@manageIncome',
          ]);

          Route::get('/checkout-sample',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@checkoutSamples',
          ]);

          Route::get('/checkout-sample/article',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@download',
          ]);

          Route::get('/checkout-sample/response/{session_id}',[
            'uses' => '\App\Http\Controllers\PaymentGateway\PaymentGatewayController@responseCheckout',
            'as' => '/checkout-sample/response'
          ]);

// Payment Gateway Route

      	Route::resource('settings','\App\Http\Controllers\Settings\SettingsController');

      	Route::post('settings/app-name/update',[
      		'as' => 'settings/app-name/update',
      		'uses' => '\App\Http\Controllers\Settings\SettingsController@appNameUpdate',
      	]);
      	Route::post('settings/app-logo/update',[
      		'as' => 'settings/app-logo/update',
      		'uses' => '\App\Http\Controllers\Settings\SettingsController@appLogoUpdate',
      	]);

      	Route::post('settings/app-theme/update',[
      		'as' => 'settings/app-theme/update',
      		'uses' => '\App\Http\Controllers\Settings\SettingsController@appThemeUpdate',
      	]);

      	Route::post('settings/stripe-payment/update',[
      		'as' => 'settings/stripe-payment/update',
      		'uses' => '\App\Http\Controllers\Settings\SettingsController@stripePaymentUpdate',
      	]);

        Route::post('settings/auth-settings/update',[
      		'as' => 'settings/auth-settings/update',
      		'uses' => '\App\Http\Controllers\Settings\SettingsController@authSettingsUpdate',
      	]);

        // Premium Content
        Route::resource('/article', '\App\Http\Controllers\Article\ArticleController');
        Route::post('/article-image', '\App\Http\Controllers\Article\ArticleController@articleImageUpload');
        Route::resource('/category-article', '\App\Http\Controllers\Article\ArticleCategoryController');
#####################################ADMIN MANAGED SECTION##########################################

#####################################CRUD GENERATOR ROUTES##########################################
      Route::get('/crud-builder', [
        'as' => 'crud-builder',
        'uses' => '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder'
      ])->middleware('auth','web','role:admin','2fa');

      Route::get('/field-template',[
        'as' => 'field-template',
        'uses' => '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate'
      ])->middleware('auth','web','role:admin','2fa');

      Route::post('/generator-builder/generate', [
        'as' => 'generator-builder/generate',

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use App\User;
use App\Role;
use App\Permission;
use App\Charts\Charts;
use Carbon\Carbon;
use Spatie\Activitylog\Models\Activity;
use App\Subscriptions;
use App\Stripe\StripeCustomer;
use \Stripe\Exception\AuthenticationException;
use \Stripe\Exception\ApiConnectionException;
use \Stripe\Exception\ApiErrorException;
use \Stripe\Exception\RateLimitException;
use \Stripe\Exception\InvalidRequestException;

class DashboardController extends Controller
{
    private $user;
    private $chart;
    private $subscriptions;
    private $stripeCustomer;


    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(Charts $chart, User $user, Subscriptions $subscriptions, StripeCustomer $stripeCustomer)
    {
        if (setting('email_verification')) {
            $this->middleware(['verified']);
        }
        $this->middleware(['auth','web','2fa']);

        $this->user = $user;

        $this->chart = $chart;
        $this->subscriptions = $subscriptions;
        $this->stripeCustomer = $stripeCustomer;
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        if ($this->isAdmin()) {
            return $this->adminDashboard();
        }

        return $this->defaultDashboard();
    }

    /**
     * return admin users to admin dashboard
     * @return [type] [description]
     */
    private function adminDashboard()
    {
        $users = User::count();
        $roles = Role::count();
        $chart = $this->userCount();
        $latest_user = $this->getLatestUsersCount();
        $latestSubscription = collect([]);
        $total_income = $this->totalIncome();

        try {
            $latestSubscription =  $this->getLatestSubscription();
        } catch (ApiConnectionException $th) {
            $error_msg = $th->getMessage();
        } catch (AuthenticationException $th) {
            $error_msg = $th->getMessage();
        } catch (InvalidRequestException $th) {
            $error_msg = $th->getMessage();
        }

        return view('dashboard.admin', [
            'latestUser'=> $this->chart,
            'users' => $users,
            'roles'=> $roles,
            'latest_users' => $latest_user,
            'latestSubscription'=> $latestSubscription,
            'total_income' => $total_income
          ]);
    }

    private function userCount()
    {
        $data = collect([]); // Could also be an array
      $label = collect([]); // Could also be an array

      for ($days_backwards = 4; $days_backwards >= 0; $days_backwards--) {
          $next_month = ($days_backwards !== 0)? $days_backwards - 1: 0;
          $data->push(User::whereBetween('created_at', [today()->subMonths($days_backwards)->startOfMonth(),today()->subMonths($days_backwards)->endOfMonth()])->count());
          $label->push(today()->subMonths($days_backwards)->format('M-y'));
      }

        $this->chart->labels($label);
        $this->chart->dataset('Registration History', 'bar', $data)
      ->backgroundColor('rgba(108, 178, 235, 0.9)');
        $this->chart->displayLegend(false);
        $this->chart->barWidth(0.4);
        return $this->chart;
    }

    /**
     * Function directs users to default dashboard
     * @return view default user dashboard
     */
    private function defaultDashboard()
    {
        return view('dashboard.default');
    }

    /**
     * Check if Authenticated user is admin
     * @return boolean [description]
     */
    private function isAdmin()
    {
        return (auth()->user()->roles->first()['name'] == 'admin')? true : false;
    }

    private function getFullname($id)
    {
        $user = $this->user->find($id);
        return ($user)? $user->fullname: null;
    }

    private function getLatestSubscription()
    {
        $subscriptions = collect([]);
        $values = $this->subscriptions->take(8)->orderByDesc('id')->get();
        foreach ($values as $val) {
            if ($this->stripeCustomer->getSubscription($val->subscription_id)) {
                $subscriptions->push([
            'id' => $val->id,
            'fullname'=>$this->getFullname($val->user_id),
            'stripe_id'=>$val->subscription_id,
            'plan_name'  => $val->plan_name,
            'amount' => $val->subscription_amount,
          ]);
            }
        }
        return collect($subscriptions);
    }

    private function getLatestUsersCount()
    {
        return $this->user->whereBetween('created_at', [
        now()->subDay(3)->toDateString(),now()->addDay()->toDateString()
      ])->count();
    }

    public function totalIncome()
    {
        // Overrall Amount Accumulated
        $overrall_income = collect($this->subscriptions->all())->map(function ($value) {
            return $value->subscription_amount;
        })->sum();

        return $overrall_income;
    }
}

resources/views/dashboard/admin.blade.php
@extends('layouts.template')

@section('title','Dashboard')

@section('content')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
		<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{__('app.dashboard')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">{{__('app.home')}}</a></li>
              <li class="breadcrumb-item active">{{__('app.dashboard')}}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

      <!-- Small boxes (Stat box) -->
      @include('layouts.includes.alerts')
      @role('admin')
      <!-- Info boxes -->
        <div class="row mb-2">
          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box shadow p-3">
              <a href="{{route('user.index')}}"  Class="info-box-icon bg-dark elevation-1" data-toggle="tooltip" data-placement="bottom" title="See All Users"><i class="fa fa-users"></i></a>

              <div class="info-box-content">
                <span class="info-box-text">{{__('app.total_users')}}</span>
                <span class="info-box-number lead">
                  {{$users}}
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->

          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box shadow p-3">
              <a href="{{route('user.index')}}"  Class="info-box-icon bg-navy elevation-1" data-toggle="tooltip" data-placement="bottom" title="See Users"><i class="fa fa-user-plus"></i></a>

              <div class="info-box-content">
                <span class="info-box-text">{{__('app.new_users')}}</span>
                <span class="info-box-number lead">
                  {{$latest_users}}
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->

          <!-- fix for small devices only -->
          <div class="clearfix hidden-md-up"></div>


          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box shadow p-3">
              <a href="{{route('role.index')}}"  Class="info-box-icon bg-primary elevation-1" data-toggle="tooltip" data-placement="bottom" title="See Roles"><i class="fa fa-tag"></i></a>

              <div class="info-box-content">
                <span class="info-box-text">{{__('app.roles')}}</span>
                <span class="info-box-number lead">
                  {{$roles}}
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->


       <div class="col-12 col-sm-6 col-md-3">
          <div class="info-box shadow p-3">
            <a href="/subscription-income"  Class="info-box-icon bg-success elevation-1" data-toggle="tooltip" data-placement="bottom" title="See Total Income"><i class="fa fa-money"></i></a>

            <div class="info-box-content">
              <span class="info-box-text">{{__('app.total_income')}}</span>
              <span class="info-box-number lead">
                @money($total_income)
              </span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->


        </div>
        <!-- /.row -->



      <div class="row">

        <div class="col-lg-7 col-xs-11 h-100 mb-3">
          <!-- small box -->
          <div class="card bg-white shadow">
            <div class="card-header bg-primary">
              {{__('app.reg_history')}}
            </div>
            <div class="card-body">
              {!! $latestUser->container() !!}
              @if($latestUser)
                {!! $latestUser->script() !!}
              @endif
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-5 col-xs-11 h-100 mb-3">
          <!-- small box -->
          <div class="card bg-white shadow">
            <div class="card-header bg-primary">
              {{__('app.recent_subscription')}}
              <span class="pull-right"><a href="/subscribed-users" class=" text-white hover-danger">View all</a></span>
            </div>
            <div class="card-body p-0">
              <div class="row">
                <div class="col-md-12">
                  <div class="table-responsive">
                  <table class="table table-hover table-striped">
                      <thead>
                        <tr>
                          <th>{{__('app.users')}}</th>
                          <th>{{__('app.plan')}}</th>
                          <th>{{__('app.amount')}}</th>
                        </tr>
                      </thead>
                      <tbody>
                      @if(setting('stripe_status'))
                        @if(count($latestSubscription) > 0)
                            @foreach($latestSubscription as $latest)
                            <tr>
                              <td>{{$latest['fullname']}}</td>
                              <td>{{$latest['plan_name']}}</td>
                              <td>@money($latest['amount'])</td>
                            </tr>
                            @endforeach
                          @else
                          <tr>
                            <td colspan="3" class="text-center text-muted"><h5><i>{{__('app.no_record')}}</i></h5></td>
                          </tr>
                        @endif
                      @else
                      <tr>
                        <td colspan="3" class="text-center text-muted">
                          <h5><i>{{__('app.payment_disabled')}}</i></h5>
                        </td>
                      </tr>
                      @endif
                      </tbody>
                    </table>
            </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- ./col -->

      </div>
		@endrole('admin')
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection

resources/views/dashboard/default.blade.php
@extends('layouts.template')

@section('title','Dashboard')

@section('content')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
		<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{__('app.dashboard')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">{{__('app.home')}}</a></li>
              <li class="breadcrumb-item active">{{__('app.dashboard')}}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
      <!-- Small boxes (Stat box) -->
      @include('layouts.includes.alerts')
      <div class="row">
		<!--============================ View for Non-Admin ============================-->
		@unlessrole('admin')

          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box shadow p-3">
              <a href="/profile"  Class="info-box-icon bg-dark elevation-1" data-toggle="tooltip" data-placement="bottom" title="See {{__('app.profile')}}"><i class="fa fa-user-circle-o"></i></a>

              <div class="info-box-content">
                <span class="info-box-text">{{__('app.profile')}}</span>
                <span class="info-box-number">
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->

          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box shadow p-3">
              <a href="/trees/add"  Class="info-box-icon bg-info elevation-1" data-toggle="tooltip" data-placement="bottom" title="See {{__('app.planted_tree')}}"><i class="fa fa-tree"></i></a>

              <div class="info-box-content">
                <span class="info-box-text">{{__('app.planted_tree')}}</span>
                <span class="info-box-number">
                  0
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->

    @endunlessrole

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection